# Usage:
#   docker build -f Dockerfile.fedora .
#   docker build -f Dockerfile.fedora --build-arg FEDORA_VERSION=41 --build-arg DDS_VERSION=3.17 .
#   docker build -f Dockerfile.fedora --build-arg BOOST_VERSION=90 .

# Stage 1: Common build environment with shared dnf packages.
ARG FEDORA_VERSION=42
FROM fedora:${FEDORA_VERSION} AS buildenv

RUN dnf -y update && \
    dnf -y install abseil-cpp-devel \
                   asio-devel \
                   ca-certificates \
                   cmake \
                   flatbuffers-devel \
                   flatbuffers-compiler \
                   fmt-devel \
                   gcc-c++ \
                   git \
                   grpc-devel \
                   grpc-plugins \
                   libxml2 \
                   ninja-build \
                   patch \
                   wget \
                   zeromq-devel

# Stage 2: Build custom dependencies from source into /usr/local.
# Source and build trees are discarded with this stage.
FROM buildenv AS build

ARG BOOST_VERSION=
ARG FAIRCMAKEMODULES_VERSION=v1.0.0
ARG FAIRLOGGER_VERSION=v2.3.1
ARG FAIRMQ_VERSION=v1.10.1
ARG DDS_VERSION=3.18

RUN if [ -n "${BOOST_VERSION}" ]; then \
        wget -O /boost.tar.gz "https://archives.boost.io/release/1.${BOOST_VERSION}.0/source/boost_1_${BOOST_VERSION}_0.tar.gz" && \
        tar xzf /boost.tar.gz && \
        cd /boost_1_${BOOST_VERSION}_0 && \
        ./bootstrap.sh --prefix=/usr/local && \
        ./b2 install -j$(nproc) --without-python --without-mpi && \
        cd / && rm -rf /boost.tar.gz /boost_1_${BOOST_VERSION}_0; \
    else \
        dnf -y install boost-devel; \
    fi

ADD --keep-git-dir=true https://github.com/FairRootGroup/FairCMakeModules.git#${FAIRCMAKEMODULES_VERSION} /FairCMakeModules
RUN cmake -GNinja -S FairCMakeModules -B FairCMakeModules_build -DCMAKE_INSTALL_PREFIX=/usr/local && \
    cmake --build FairCMakeModules_build --target install

ADD --keep-git-dir=true https://github.com/FairRootGroup/FairLogger.git#${FAIRLOGGER_VERSION} /FairLogger
RUN cmake -GNinja -S FairLogger -B FairLogger_build -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release && \
    cmake --build FairLogger_build --target install

ADD --keep-git-dir=true https://github.com/FairRootGroup/FairMQ.git#${FAIRMQ_VERSION} /FairMQ
RUN cmake -GNinja -S FairMQ -B FairMQ_build -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release && \
    cmake --build FairMQ_build --target install

ADD https://github.com/FairRootGroup/DDS.git#${DDS_VERSION} /DDS
RUN echo "${DDS_VERSION}" > /DDS/version && \
    cmake -GNinja -S DDS -B DDS_build -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_dds-tutorials=OFF && \
    cmake --build DDS_build --target wn_bin && \
    cmake --build DDS_build --target install

# Stage 3: Final image with ODC-specific build dependencies
# and the install trees of the custom-built dependencies from stage 2.
FROM buildenv AS odc

ARG BOOST_VERSION=
RUN if [ -z "${BOOST_VERSION}" ]; then dnf -y install boost-devel; fi && \
    dnf -y install clang-tools-extra \
                   libasan \
                   liblsan \
                   libubsan && \
    dnf -y clean all

COPY --from=build /usr/local /usr/local

# Stage 4: Build Slurm from source (matching sind's reference image)
FROM buildenv AS slurm-builder

ARG SLURM_VERSION=25.11.4

RUN dnf -y install \
        munge-devel \
        pam-devel \
        readline-devel \
        perl-ExtUtils-MakeMaker \
        python3 \
        mariadb-devel \
        dbus-devel \
        libbpf-devel \
        tar bzip2

ADD --checksum=sha256:237f515adcb37b99ff6cb3e1fa81691a5f7188e94c3b6b495858b4eaecf6531d \
    https://download.schedmd.com/slurm/slurm-${SLURM_VERSION}.tar.bz2 /tmp/slurm.tar.bz2

WORKDIR /tmp
RUN tar xf slurm.tar.bz2 && \
    cd slurm-${SLURM_VERSION} && \
    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc/slurm \
        --localstatedir=/var \
        --runstatedir=/run \
        --with-munge \
        --with-pam_dir=/usr/lib64/security \
        --with-systemdsystemunitdir=/usr/lib/systemd/system && \
    make -j$(nproc) && \
    DESTDIR=/slurm-install make install && \
    mkdir -p /slurm-install/etc

# Stage 5: sind-compatible Slurm node image for integration testing.
# Combines the ODC build environment with a source-built Slurm.
FROM odc AS sind-node

RUN dnf -y install \
        systemd \
        openssh-server \
        openssh-clients \
        munge \
        readline \
        pam \
        procps-ng \
        iproute \
        hostname \
        dbus-libs \
 && dnf -y clean all

COPY --from=slurm-builder /slurm-install/usr /usr
COPY --from=slurm-builder /slurm-install/etc /etc

RUN useradd -r -s /sbin/nologin slurm

RUN mkdir -p \
        /var/log/slurm \
        /var/spool/slurmctld \
        /var/spool/slurmd \
        /data && \
    chown -R slurm:slurm \
        /var/log/slurm \
        /var/spool/slurmctld \
        /var/spool/slurmd

RUN mkdir -p /etc/munge /var/lib/munge /var/log/munge /run/munge && \
    chown -R munge:munge /etc/munge /var/lib/munge /var/log/munge /run/munge && \
    chmod 700 /etc/munge /var/lib/munge /var/log/munge /run/munge

RUN ssh-keygen -A && \
    mkdir -p /run/sshd && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh

RUN systemctl enable munge sshd

RUN systemctl mask \
        dev-hugepages.mount \
        sys-fs-fuse-connections.mount \
        systemd-logind.service \
        getty.target \
        console-getty.service

VOLUME ["/etc/slurm", "/etc/munge", "/data"]
WORKDIR /data
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
